services:
  db:
    image: postgres:16
    restart: always
    container_name: ncpg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: data
    ports:
      - "666:5432"
