[phase.setup]
nixPkgs = ["...", "pnpm"]
cmds = ["pnpm install"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["pnpm install"]

[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "node dist"
