[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["...", "pnpm"]

[build.nixpacksPlan.phases.install]
cmds = ["pnpm install"]

[deploy]
startCommand = "node dist"
